config/routes.rb
Rails.application.routes.draw do
  root 'newscasts#index'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  namespace :admin_user do
    resources :newscasts
  end

  resources :newscasts, only: %i[index show]

  get '*path', to: 'newscasts#index', via: :all

  # get '*path', to: redirect('/'), constraints: lambda { |req|
  #   req.path.exclude? 'rails/active_storage'
  # }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/newscast.rb
class Newscast < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :image, presence: true
  # has_one_attached :image, dependent: :destroy

  # validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg'], size_range: 1..(5.megabytes) }
end

app/controllers/admin_user/newscasts_controller.rb
module AdminUser
  class NewscastsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_newscast, only: %i[ show edit update destroy ]

    # GET /newscasts or /newscasts.json
    def index
      @newscasts = Newscast.all.order(created_at: :desc)
    end

    # GET /newscasts/1 or /newscasts/1.json
    def show
    end

    # GET /newscasts/new
    def new
      @newscast = Newscast.new
    end

    # GET /newscasts/1/edit
    def edit
    end

    # POST /newscasts or /newscasts.json
    def create
      @newscast = Newscast.new(newscast_params)

      respond_to do |format|
        if @newscast.save
          format.html { redirect_to admin_user_newscasts_url(@newscasts), notice: "Newscast was successfully created." }
          format.json { render :show, status: :created, location: @newscast }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @newscast.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /newscasts/1 or /newscasts/1.json
    def update
      respond_to do |format|
        if @newscast.update(newscast_params)
          format.html { redirect_to admin_user_newscast_url(@newscast), notice: "Newscast was successfully updated." }
          format.json { render :show, status: :ok, location: @newscast }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @newscast.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /newscasts/1 or /newscasts/1.json
    def destroy
      @newscast.destroy

      respond_to do |format|
        format.html { redirect_to admin_user_newscasts_url, notice: "Newscast was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_newscast
        @newscast = Newscast.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def newscast_params
        params.require(:newscast).permit(:title, :description, :image, :attachment)
      end
  end
end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def after_sign_up_path_for(resource)
    admin_user_newscasts_path
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  private

  def after_sign_in_path_for(resource)
    admin_user_newscasts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/newscasts_controller.rb
class NewscastsController < ApplicationController
  def index
    @newscasts = Newscast.all.order(created_at: :desc)
    respond_to do |format|
      format.html
      format.json { render json: NewscastSerializer.new(@newscasts).serializable_hash[:data], status: :ok }
    end
  end

  def show
    @newscast = Newscast.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: NewscastSerializer.new(@newscast).serializable_hash[:data][:attributes], status: :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newscasts_helper.rb
module NewscastsHelper
end

app/views/admin_user/newscasts/_form.html.erb
<%= form_with(model: [:admin_user, newscast]) do |form| %>
  <% if newscast.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(newscast.errors.count, "error" ) %> prohibited this newscast from being saved:
      </h2>
      <ul>
        <% newscast.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_user/newscasts/edit.html.erb
<h1>Editing Newscast</h1>

<%= render 'form' , newscast: @newscast %>

  <%= link_to 'Show' , [ :admin_user, @newscast ] %> |
  <%= link_to 'Back' , admin_user_newscasts_path %>

app/views/admin_user/newscasts/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<div>
  <% if admin_signed_in? %>
    <span><%= button_to 'Sign Out', destroy_admin_session_path, method: :delete %></span>
  <% else %>
    <span><%= link_to 'Sign In', new_admin_session_path %></span>
    <span><%= link_to 'Sign Up', new_admin_registration_path %></span>
  <% end %>
</div>

<h1 class="newscast-title">Last News</h1>

<table class="table">
  <thead>
    <tr>
			<th>Time</th>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th>Show</th>
			<th>Edit</th>
			<th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @newscasts.each do |newscast| %>
      <tr id="options" data-controller="visibility">
        <td data-visibility-target="hideable">
          <%= newscast.created_at %>
        </td>
        <td data-visibility-target="hideable">
          <%= newscast.title %>
        </td>
        <td data-visibility-target="hideable">
          <%= newscast.description %>
        </td>
        <td data-visibility-target="hideable">
          <% if newscast.image_url %>
            <%= image_tag newscast.image_url, style: "width: 200px" %>
          <% end %>
        </td>
        <td data-visibility-target="hideable">
          <%= link_to 'Show', admin_user_newscast_path(newscast) %>
        </td>
        <td data-visibility-target="hideable">
          <%= link_to 'Edit', edit_admin_user_newscast_path(newscast) %>
        </td>
        <td data-visibility-target="hideable">
          <%= link_to 'Destroy', admin_user_newscast_path(newscast), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        <td data-visibility-target="hideable">
          <button data-action="visibility#hideTargets">Hide newscast</button>
        </td>
        <td>
          <button data-action="visibility#toggleTargets">Show newscast</button>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newscast', new_admin_user_newscast_path , class: "button" %>

app/views/admin_user/newscasts/new.html.erb
<h1>New Newscast</h1>

<%= render 'form' , newscast: @newscast %>

<%= link_to 'Back' , admin_user_newscasts_path %>

app/views/admin_user/newscasts/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<h1 class="title"><%= @newscast.title %></h1>

<p>
  <% if @newscast.image_url %>
    <%= image_tag @newscast.image_url, style: "width: 200px; display: block", class: "newscast-image" %>
  <% end %>
</p>

<p class="description">
  <%= @newscast.description %>
</p>

<%= link_to 'Edit' , edit_admin_user_newscast_path(@newscast) %> |
<%= link_to 'Back' , admin_user_newscasts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyNews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>